### ISSUE TITLE
FR: Remove keypress requirement

### ISSUE THREAD

**Issue by noon92** [markbirss/nRF52_Internal_Format#1]
As this now boots back into DFU, a flash erase loop is no longer an issue, and the keypress requirement is no longer necessary, IMO.

**Comment by markbirss** [comment]
> As this now boots back into DFU, a flash erase loop is no longer an issue, and the keypress requirement is no longer necessary, IMO.

Sure here updated files, and notes

https://github.com/markbirss/nRF52_Internal_Format/blob/main/Meshtastic_nRF52_factory_erase_v3/notes.txt

https://github.com/markbirss/nRF52_Internal_Format/blob/main/Meshtastic_nRF52_factory_erase_v3/S140_6.1.0/Meshtastic_nRF52_factory_erase_v3_S140_6.1.0.uf2

https://github.com/markbirss/nRF52_Internal_Format/blob/main/Meshtastic_nRF52_factory_erase_v3/S140_7.3.0/Meshtastic_nRF52_factory_erase_v3_S140_7.3.0.uf2
